local b = require("lib.binds")

local main_mod = "SUPER"
local alt_mod = "ALT"

-- Avoid unused warnings while documenting the canonical mod names.
local _ = { main_mod, alt_mod }

b.bind("SUPER + 1", "workspace", "1", {})
b.bind("SUPER + 2", "workspace", "2", {})
b.bind("SUPER + 3", "workspace", "3", {})
b.bind("SUPER + 4", "workspace", "4", {})
b.bind("SUPER + 5", "workspace", "5", {})
b.bind("SUPER + 6", "workspace", "6", {})
b.bind("SUPER + 7", "workspace", "7", {})
b.bind("SUPER + 8", "workspace", "8", {})
b.bind("SUPER + 9", "workspace", "9", {})
b.bind("SUPER + 0", "workspace", "10", {})
b.bind("SUPER + SHIFT + 1", "movetoworkspace", "1", {})
b.bind("SUPER + SHIFT + 2", "movetoworkspace", "2", {})
b.bind("SUPER + SHIFT + 3", "movetoworkspace", "3", {})
b.bind("SUPER + SHIFT + 4", "movetoworkspace", "4", {})
b.bind("SUPER + SHIFT + 5", "movetoworkspace", "5", {})
b.bind("SUPER + SHIFT + 6", "movetoworkspace", "6", {})
b.bind("SUPER + SHIFT + 7", "movetoworkspace", "7", {})
b.bind("SUPER + SHIFT + 8", "movetoworkspace", "8", {})
b.bind("SUPER + SHIFT + 9", "movetoworkspace", "9", {})
b.bind("SUPER + SHIFT + 0", "movetoworkspace", "10", {})
b.bind("SUPER + SHIFT + minus", "movetoworkspace", "special", {})
b.bind("SUPER + minus", "togglespecialworkspace", "", {})
b.bind("SUPER + Tab", "workspace", "previous", {})
b.bind("SUPER + SHIFT + Tab", "workspace", "e+1", {})
b.bind("SUPER + Return", "exec", "uwsm app -- kitty", {})
b.bind("SUPER + SHIFT + Q", "killactive", "", {})
b.bind("SUPER + C", "centerwindow", "", {})
b.bind("SUPER + SHIFT + X", "pin", "", {})
b.bind("SUPER + D", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette toggle", {})
b.bind("SUPER + bracketright", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory Windows", {})
b.bind("SUPER + period", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory Emoji", {})
b.bind("SUPER + P", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory Pass", {})
b.bind("SUPER + SHIFT + K", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory bind", {})
b.bind("SUPER + SHIFT + E", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory System", {})
b.bind("SUPER + T", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call tactile toggle", {})
b.bind("SUPER + SHIFT + F", "exec", "uwsm app -- nemo", {})
b.bind("SUPER + G", "exec", "uwsm app -- gtk-launch Grok", {})
b.bind("SUPER + W", "exec", "uwsm app -- zen-browser", {})
b.bind("SUPER + Y", "exec", "uwsm app -- footclient -s \"$XDG_RUNTIME_DIR/foot.sock\" -a clipse-float --title clipse clipse", {})
b.bind("SUPER + slash", "exec", "~/.local/bin/hypr_scripts/show-cheatsheet.sh", {})
b.bind("SUPER + M", "exec", "uwsm app -- footclient -s \"$XDG_RUNTIME_DIR/foot.sock\" -a ncmpcpp-float --title ncmpcpp ncmpcpp", {})
b.bind("SUPER + S", "exec", "~/.local/bin/hypr_scripts/screenshot-notify.sh region file-clipboard", {})
b.bind("SUPER + CTRL + S", "exec", "~/.local/bin/hypr_scripts/screenshot-notify.sh region clipboard", {})
b.bind("SUPER + ALT + S", "exec", "~/.local/bin/hypr_scripts/screenshot-notify.sh region satty-clipboard", {})
b.bind("SUPER + SHIFT + S", "exec", "~/.local/bin/hypr_scripts/screenshot-notify.sh fullscreen file-clipboard", {})
b.bind("SUPER + CTRL + SHIFT + S", "exec", "~/.local/bin/hypr_scripts/screenshot-notify.sh fullscreen clipboard", {})
b.bind("SUPER + ALT + U", "exec", "~/.config/hypr/scripts/screenrecord-menu.sh", {})
b.bind("SUPER + CTRL + ALT + L", "exec", "~/.local/bin/hypr_scripts/emergency-lock.sh", {})
b.bind("SUPER + CTRL + L", "exec", "~/.local/bin/hypr_scripts/aerial-hyprlock.sh", {})
b.bind("SUPER + SHIFT + CTRL + L", "exec", "~/.local/bin/hypr_scripts/lock-fallback.sh", {})
b.bind("ALT + Tab", "cyclenext", "", {})
b.bind("SUPER + J", "movefocus", "l", {})
b.bind("SUPER + K", "movefocus", "d", {})
b.bind("SUPER + L", "movefocus", "u", {})
b.bind("SUPER + semicolon", "movefocus", "r", {})
b.bind("SUPER + left", "movefocus", "l", {})
b.bind("SUPER + down", "movefocus", "d", {})
b.bind("SUPER + up", "movefocus", "u", {})
b.bind("SUPER + right", "movefocus", "r", {})
b.bind("SUPER + SHIFT + J", "movewindow", "l", {})
b.bind("SUPER + SHIFT + L", "movewindow", "u", {})
b.bind("SUPER + SHIFT + semicolon", "movewindow", "r", {})
b.bind("SUPER + SHIFT + left", "movewindow", "l", {})
b.bind("SUPER + SHIFT + down", "movewindow", "d", {})
b.bind("SUPER + SHIFT + up", "movewindow", "u", {})
b.bind("SUPER + SHIFT + right", "movewindow", "r", {})
b.bind("SUPER + H", "layoutmsg", "togglesplit", {})
b.bind("SUPER + F", "fullscreen", "0", {})
b.bind("SUPER + A", "pseudo", "", {})
b.bind("SUPER + SHIFT + space", "togglefloating", "", {})
b.bind("SUPER + space", "cyclenext", "", {})
local border_size = 2

b.bind("SUPER + U", function()
  border_size = border_size == 0 and 2 or 0
  hl.config({ general = { border_size = border_size } })
end, nil, {})
b.bind("SUPER + ALT + W", "exec", "MONITOR=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true) | .name') && awww img \"$(find /home/rx/Pictures/backgrnds/ -type f \\( -name '*.jpg' -o -name '*.png' \\) 2>/dev/null | shuf -n 1)\" --outputs \"$MONITOR\" --transition-type random && uwsm app -- notify-send -t 2500 \"Wallpaper Updated on $MONITOR\"", {})
b.bind("SUPER + SHIFT + W", "exec", "skwd wall toggle", {})
b.bind("SUPER + SHIFT + B", "exec", "/home/rx/.config/warmind/launcher/bin/bluetooth-power-toggle.sh", {})
b.bind("SUPER + CTRL + V", "exec", "voxtype record toggle", {})
b.bind("SUPER + CTRL + SHIFT + V", "exec", "voxtype record cancel", {})
b.bind("CTRL + ALT + F1", "exec", "wlopm --on '*'", {})
b.bind("XF86AudioRaiseVolume", "exec", "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+", { repeatable = true, locked = true })
b.bind("XF86AudioLowerVolume", "exec", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-", { repeatable = true, locked = true })
b.bind("XF86AudioMute", "exec", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle", { repeatable = true, locked = true })
b.bind("XF86AudioMicMute", "exec", "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle", { repeatable = true, locked = true })
b.bind("XF86AudioPlay", "exec", "playerctl play-pause", { locked = true })
b.bind("XF86AudioPrev", "exec", "playerctl previous", { locked = true })
b.bind("XF86AudioNext", "exec", "playerctl next", { locked = true })
b.bind("SUPER + mouse:272", "movewindow", "", { mouse = true })
b.bind("SUPER + mouse:273", "resizewindow", "", { mouse = true })
local function enter_submap(name, label)
  return function()
    hl.dispatch(hl.dsp.exec_cmd('dunstify -t 2000 "Mode: ' .. label .. '" "Press ESC or Enter to exit" -h string:x-dunst-stack-tag:hypr-mode'))
    hl.dispatch(hl.dsp.submap(name))
  end
end

b.bind("SUPER + R", enter_submap("resize", "Resize"), nil, {})
b.bind("SUPER + SHIFT + G", enter_submap("gaps", "Gaps"), nil, {})

b.submap("resize", function()
  b.bind("H", "resizeactive", "-50 0", { repeatable = true })
  b.bind("J", "resizeactive", "0 50", { repeatable = true })
  b.bind("K", "resizeactive", "0 -50", { repeatable = true })
  b.bind("L", "resizeactive", "50 0", { repeatable = true })
  b.bind("SHIFT + H", "resizeactive", "-100 0", { repeatable = true })
  b.bind("SHIFT + J", "resizeactive", "0 100", { repeatable = true })
  b.bind("SHIFT + K", "resizeactive", "0 -100", { repeatable = true })
  b.bind("SHIFT + L", "resizeactive", "100 0", { repeatable = true })
  b.bind("CTRL + H", "resizeactive", "-200 0", { repeatable = true })
  b.bind("CTRL + J", "resizeactive", "0 200", { repeatable = true })
  b.bind("CTRL + K", "resizeactive", "0 -200", { repeatable = true })
  b.bind("CTRL + L", "resizeactive", "200 0", { repeatable = true })
  b.bind("SHIFT + CTRL + H", "resizeactive", "-300 0", { repeatable = true })
  b.bind("SHIFT + CTRL + J", "resizeactive", "0 300", { repeatable = true })
  b.bind("SHIFT + CTRL + K", "resizeactive", "0 -300", { repeatable = true })
  b.bind("SHIFT + CTRL + L", "resizeactive", "300 0", { repeatable = true })
  b.bind("left", "resizeactive", "-50 0", { repeatable = true })
  b.bind("down", "resizeactive", "0 50", { repeatable = true })
  b.bind("up", "resizeactive", "0 -50", { repeatable = true })
  b.bind("right", "resizeactive", "50 0", { repeatable = true })
  b.bind("SHIFT + left", "resizeactive", "-100 0", { repeatable = true })
  b.bind("SHIFT + down", "resizeactive", "0 100", { repeatable = true })
  b.bind("SHIFT + up", "resizeactive", "0 -100", { repeatable = true })
  b.bind("SHIFT + right", "resizeactive", "100 0", { repeatable = true })
  b.bind("CTRL + left", "resizeactive", "-200 0", { repeatable = true })
  b.bind("CTRL + down", "resizeactive", "0 200", { repeatable = true })
  b.bind("CTRL + up", "resizeactive", "0 -200", { repeatable = true })
  b.bind("CTRL + right", "resizeactive", "200 0", { repeatable = true })
  b.bind("SHIFT + CTRL + left", "resizeactive", "-300 0", { repeatable = true })
  b.bind("SHIFT + CTRL + down", "resizeactive", "0 300", { repeatable = true })
  b.bind("SHIFT + CTRL + up", "resizeactive", "0 -300", { repeatable = true })
  b.bind("SHIFT + CTRL + right", "resizeactive", "300 0", { repeatable = true })
  b.bind("Return", "submap", "reset", {})
  b.bind("Escape", "submap", "reset", {})
end)

b.submap("gaps", function()
  b.bind("O", function()
    hl.dispatch(hl.dsp.submap("gaps_outer"))
  end, nil, {})
  b.bind("I", function()
    hl.dispatch(hl.dsp.submap("gaps_inner"))
  end, nil, {})
  b.bind("Return", "submap", "reset", {})
  b.bind("Escape", "submap", "reset", {})
end)

local gaps_out = 12
local gaps_in = 5

local function set_gap(name, value)
  return function()
    if name == "gaps_out" then
      gaps_out = math.max(0, value(gaps_out))
      hl.dispatch(function()
        hl.config({ general = { gaps_out = gaps_out } })
      end)
    else
      gaps_in = math.max(0, value(gaps_in))
      hl.dispatch(function()
        hl.config({ general = { gaps_in = gaps_in } })
      end)
    end
  end
end

b.submap("gaps_outer", function()
  b.bind("8", set_gap("gaps_out", function(value) return value + 5 end), nil, { repeatable = true })
  b.bind("9", set_gap("gaps_out", function(value) return value - 5 end), nil, { repeatable = true })
  b.bind("0", set_gap("gaps_out", function() return 0 end), nil, {})
  b.bind("6", set_gap("gaps_out", function(value) return value + 5 end), nil, { repeatable = true })
  b.bind("7", set_gap("gaps_out", function(value) return value - 5 end), nil, { repeatable = true })
  b.bind("5", set_gap("gaps_out", function() return 0 end), nil, {})
  b.bind("Return", "submap", "reset", {})
  b.bind("Escape", "submap", "reset", {})
end)

b.submap("gaps_inner", function()
  b.bind("8", set_gap("gaps_in", function(value) return value + 5 end), nil, { repeatable = true })
  b.bind("9", set_gap("gaps_in", function(value) return value - 5 end), nil, { repeatable = true })
  b.bind("0", set_gap("gaps_in", function() return 0 end), nil, {})
  b.bind("6", set_gap("gaps_in", function(value) return value + 5 end), nil, { repeatable = true })
  b.bind("7", set_gap("gaps_in", function(value) return value - 5 end), nil, { repeatable = true })
  b.bind("5", set_gap("gaps_in", function() return 0 end), nil, {})
  b.bind("Return", "submap", "reset", {})
  b.bind("Escape", "submap", "reset", {})
end)

b.submap("calendar", function()
  b.bind("left", "exec", "~/.config/waybar/scripts/calendar_daemon.py --prev", {})
  b.bind("right", "exec", "~/.config/waybar/scripts/calendar_daemon.py --next", {})
  b.bind("h", "exec", "~/.config/waybar/scripts/calendar_daemon.py --prev", {})
  b.bind("l", "exec", "~/.config/waybar/scripts/calendar_daemon.py --next", {})
  b.bind("t", "exec", "~/.config/waybar/scripts/calendar_daemon.py --init", {})
  b.bind("Escape", "exec", "pkill -x waycal", {})
  b.bind("Escape", "submap", "reset", {})
  b.bind("q", "exec", "pkill -x waycal", {})
  b.bind("q", "submap", "reset", {})
end)
