-- Generated by Warmind Launcher. Do not edit manually.
-- Source repo: /home/rx/Projects/warmind_launcher
-- Native Hyprland Lua integration. Requires Hyprland >= 0.55.

local b = require("lib.binds")

local repeat_locked = { repeatable = true, locked = true }
local locked = { locked = true }

hl.unbind("SUPER + D")
hl.unbind("SUPER + P")
hl.unbind("SUPER + T")
hl.unbind("SUPER + bracketright")
hl.unbind("SUPER + period")
hl.unbind("SUPER + SHIFT + K")
hl.unbind("SUPER + SHIFT + E")
hl.unbind("SUPER + SHIFT + B")
hl.unbind("SUPER + grave")
hl.unbind("XF86AudioRaiseVolume")
hl.unbind("XF86AudioLowerVolume")
hl.unbind("XF86AudioMute")
hl.unbind("XF86AudioMicMute")
hl.unbind("XF86AudioPlay")
hl.unbind("XF86AudioPrev")
hl.unbind("XF86AudioNext")

b.bind("SUPER + D", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette toggle", {})
b.bind("SUPER + bracketright", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory Windows", {})
b.bind("SUPER + period", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory Emoji", {})
b.bind("SUPER + P", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory Pass", {})
b.bind("SUPER + SHIFT + K", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory bind", {})
b.bind("SUPER + SHIFT + E", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call palette openCategory System", {})
b.bind("SUPER + SHIFT + B", "exec", "/home/rx/.config/warmind/launcher/bin/bluetooth-power-toggle.sh", {})
b.bind("SUPER + T", "exec", "uwsm app -- qs -c /home/rx/.config/warmind/launcher ipc call tactile toggle", {})
-- b.bind("SUPER + grave", "exec", "/home/rx/.config/warmind/launcher/bin/expose-toggle.sh", {})

b.bind("XF86AudioRaiseVolume", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-audio-key.sh raise", repeat_locked)
b.bind("XF86AudioLowerVolume", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-audio-key.sh lower", repeat_locked)
b.bind("XF86AudioMute", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-audio-key.sh mute", repeat_locked)
b.bind("XF86AudioMicMute", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-audio-key.sh mic-mute", repeat_locked)
b.bind("XF86AudioPlay", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-media-key.sh play-pause", locked)
b.bind("XF86AudioPrev", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-media-key.sh previous", locked)
b.bind("XF86AudioNext", "exec", "/home/rx/.config/warmind/launcher/bin/warmind-media-key.sh next", locked)

hl.window_rule({ name = "warmind-system-update", match = { title = [[^(Warmind System Update)$]] }, float = true, center = true, size = "1100 820" })
hl.window_rule({ name = "warmind-user-password", match = { title = [[^(Warmind User Password)$]] }, float = true, center = true, size = "900 520" })
hl.window_rule({ name = "warmind-install-package", match = { title = [[^(Warmind Install Package)$]] }, float = true, center = true, size = "1237 870" })
hl.window_rule({ name = "warmind-setup-terminal", match = { title = [[^Warmind Setup: .*$]] }, float = true, center = true, size = "1180 820" })
hl.window_rule({ name = "warmind-setup-bluetooth", match = { title = [[^(Warmind Setup: Bluetooth)$]] }, float = true, center = true, size = "860 720" })
hl.window_rule({ name = "warmind-setup-audio", match = { class = [[^org\.pulseaudio\.pavucontrol$]] }, float = true, center = true, size = "1100 760" })
hl.window_rule({ name = "warmind-learn-hyprland-wiki", match = { class = [[^brave-wiki\.hypr\.land__-Default$]] }, float = true, center = true, size = "1280 1340", tag = "+chrome-webapp" })
hl.window_rule({ name = "warmind-learn-arch-wiki", match = { class = [[^brave-wiki\.archlinux\.org__-Default$]] }, float = true, center = true, size = "1280 1340", tag = "+chrome-webapp" })
hl.window_rule({ name = "warmind-learn-quickshell-docs", match = { class = [[^brave-quickshell\.outfoxxed\.me__docs-Default$]] }, float = true, center = true, size = "1280 1340", tag = "+chrome-webapp" })
