import QtQuick
import Quickshell
import Quickshell.Io

// Network detail. In Wi-Fi mode it keeps the original iwd-driven radio
// toggle + scan + SSID list. In Ethernet mode it shows a read-only text
// report generated by a small shell script that mirrors the useful
// details from the active Waybar network tooltip.
Item {
    id: body
    required property var root
    required property var nav
    required property var controller
    width: parent ? parent.width : 0

    signal close()

    implicitHeight: col.implicitHeight + 8
    readonly property bool wifiCapable: !!(body.controller && body.controller.supported)
    readonly property bool ethernetMode: !body.wifiCapable || (body.nav && body.nav.netKind === "eth")
    property string ethernetDetails: "LOADING…"

    Component.onCompleted: {
        if (body.controller) body.controller.refresh();
        if (!body.nav) return;
        if (body.ethernetMode) body.refreshEthernetDetails();
    }
    onEthernetModeChanged: {
        body.kbdIndex = body.ethernetMode ? 0 : 2;
        if (!body.nav) return;
        if (body.ethernetMode) body.refreshEthernetDetails();
        else if (body.controller) body.controller.refresh();
    }

    // Ethernet: 0 = REFRESH
    // Wi-Fi:    0 = RADIO toggle, 1 = SCAN, 2..N+1 = network rows
    property int kbdIndex: ethernetMode ? 0 : 2
    readonly property int _headerCount: 2
    readonly property var _visibleNets: (!body.ethernetMode && body.controller && body.controller.radioOn)
                                        ? body.controller.networks.slice(0, 8)
                                        : []
    readonly property int _kbdMax: body.ethernetMode ? 1 : (_headerCount + _visibleNets.length)

    Process {
        id: ethernetProbe
        running: false
        command: ["bash", "-lc", Quickshell.env("HOME") + "/.config/warmind/launcher/bin/network-details.sh"]
        stdout: StdioCollector {
            onStreamFinished: {
                const txt = this.text.trim();
                body.ethernetDetails = txt.length > 0 ? txt : "NO NETWORK DETAILS AVAILABLE";
            }
        }
    }

    function refreshEthernetDetails() {
        body.ethernetDetails = "LOADING…";
        ethernetProbe.running = false;
        ethernetProbe.running = true;
    }

    function kbdHandle(event) {
        const k = event.key;
        const n = body._kbdMax;
        if (n === 0) return false;

        if (body.ethernetMode) {
            if (k === Qt.Key_Up || k === Qt.Key_Left) {
                body.kbdIndex = Math.max(0, body.kbdIndex - 1);
                return true;
            }
            if (k === Qt.Key_Down || k === Qt.Key_Right || k === Qt.Key_Tab) {
                body.kbdIndex = Math.min(n - 1, body.kbdIndex + 1);
                return true;
            }
            if (k === Qt.Key_Return || k === Qt.Key_Enter || k === Qt.Key_Space) {
                body.refreshEthernetDetails();
                return true;
            }
            return false;
        }

        if (k === Qt.Key_Up) {
            body.kbdIndex = Math.max(0, body.kbdIndex - 1);
            return true;
        }
        if (k === Qt.Key_Down || k === Qt.Key_Tab) {
            body.kbdIndex = Math.min(n - 1, body.kbdIndex + 1);
            return true;
        }
        if (k === Qt.Key_Left) {
            body.kbdIndex = Math.max(0, body.kbdIndex - 1);
            return true;
        }
        if (k === Qt.Key_Right) {
            body.kbdIndex = Math.min(n - 1, body.kbdIndex + 1);
            return true;
        }
        if (k === Qt.Key_Return || k === Qt.Key_Enter || k === Qt.Key_Space) {
            body._activateAt(body.kbdIndex);
            return true;
        }
        return false;
    }

    function _activateAt(i) {
        body.kbdIndex = i;
        if (i === 0) { if (body.controller) body.controller.toggleRadio(); return; }
        if (i === 1) { if (body.controller) body.controller.refresh(); return; }
        const net = body._visibleNets[i - body._headerCount];
        if (!net || !body.controller) return;
        if (net.inUse) body.controller.disconnect();
        else body.controller.connect(net.ssid);
    }

    Column {
        id: col
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.topMargin: 6
        spacing: 10

        Item {
            width: parent.width
            height: 28

            Text {
                anchors.left: parent.left
                anchors.verticalCenter: parent.verticalCenter
                text: body.ethernetMode
                      ? (body.wifiCapable ? "ETHERNET DETAILS" : "NETWORK DETAILS")
                      : (body.controller && body.controller.radioOn
                         ? (body.controller.scanning ? "SCANNING…"
                            : (body.controller.networks.length + " NETWORKS"))
                         : "RADIO OFF")
                color: body.root.inkDeep
                font.family: body.root.mono
                font.pixelSize: 10
                font.letterSpacing: 2
            }
            Row {
                anchors.right: parent.right
                anchors.verticalCenter: parent.verticalCenter
                spacing: 8

                QuickButton {
                    visible: body.ethernetMode
                    root: body.root
                    glyph: body.nav ? body.nav.icoRefresh : ""
                    label: "REFRESH"
                    selected: body.ethernetMode && body.kbdIndex === 0
                    onClicked: body.refreshEthernetDetails()
                }
                QuickButton {
                    visible: !body.ethernetMode
                    root: body.root
                    label: body.controller && body.controller.radioOn ? "RADIO OFF" : "RADIO ON"
                    selected: !body.ethernetMode && body.kbdIndex === 0
                    onClicked: if (body.controller) body.controller.toggleRadio()
                }
                QuickButton {
                    visible: !body.ethernetMode
                    root: body.root
                    glyph: body.nav ? body.nav.icoRefresh : ""
                    label: "SCAN"
                    selected: !body.ethernetMode && body.kbdIndex === 1
                    onClicked: if (body.controller) body.controller.refresh()
                }
            }
        }

        Rectangle { width: parent.width; height: 1; color: body.root.sep }

        Rectangle {
            visible: body.ethernetMode
            width: parent.width
            height: ethText.implicitHeight + 22
            radius: body.root.cornerRadius
            color: Qt.rgba(body.root.ink.r, body.root.ink.g, body.root.ink.b, 0.03)
            border.color: body.root.sep
            border.width: 1

            Text {
                id: ethText
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.top: parent.top
                anchors.margins: 11
                text: body.ethernetDetails
                textFormat: Text.PlainText
                wrapMode: Text.Wrap
                color: body.root.ink
                font.family: body.root.mono
                font.pixelSize: 11
                lineHeight: 1.15
            }
        }

        Repeater {
            visible: !body.ethernetMode
            model: body._visibleNets
            delegate: Rectangle {
                required property var modelData
                required property int index
                readonly property bool kbdFocused: body.kbdIndex === (index + body._headerCount)
                width: col.width
                height: 32
                radius: body.root.cornerRadius
                color: modelData.inUse || kbdFocused
                       ? body.root.rowSel
                       : netMouse.containsMouse
                           ? body.root.rowHi
                           : "transparent"
                border.color: modelData.inUse || kbdFocused ? body.root.seal : body.root.sep
                border.width: kbdFocused ? 2 : 1
                Behavior on color        { ColorAnimation { duration: 120 } }
                Behavior on border.color { ColorAnimation { duration: 120 } }
                Behavior on border.width { NumberAnimation { duration: 120 } }

                Text {
                    id: barsIcon
                    anchors.left: parent.left
                    anchors.leftMargin: 10
                    anchors.verticalCenter: parent.verticalCenter
                    text: body.nav.wifiBarsGlyph(modelData.signal)
                    color: modelData.inUse ? body.root.seal : body.root.ink
                    font.family: body.root.mono
                    font.pixelSize: 14
                }
                Text {
                    anchors.left: barsIcon.right
                    anchors.right: secTag.left
                    anchors.leftMargin: 10
                    anchors.rightMargin: 10
                    anchors.verticalCenter: parent.verticalCenter
                    text: modelData.ssid
                    elide: Text.ElideRight
                    color: modelData.inUse ? body.root.ink : body.root.fg
                    font.family: body.root.mono
                    font.pixelSize: 11
                    font.weight: modelData.inUse ? Font.Medium : Font.Normal
                }
                Text {
                    id: secTag
                    anchors.right: sigText.left
                    anchors.rightMargin: 10
                    anchors.verticalCenter: parent.verticalCenter
                    text: modelData.security && modelData.security.length > 0
                          && modelData.security !== "open" ? "󰌾" : ""
                    color: body.root.inkDeep
                    font.family: body.root.mono
                    font.pixelSize: 11
                }
                Text {
                    id: sigText
                    anchors.right: parent.right
                    anchors.rightMargin: 10
                    anchors.verticalCenter: parent.verticalCenter
                    text: modelData.signal + "%"
                    color: body.root.inkDeep
                    font.family: body.root.mono
                    font.pixelSize: 10
                    font.letterSpacing: 1
                }
                MouseArea {
                    id: netMouse
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: body._activateAt(index + body._headerCount)
                }
            }
        }

        Text {
            visible: !body.ethernetMode && body.controller && body.controller.radioOn && body.controller.networks.length === 0 && !body.controller.scanning
            width: parent.width
            horizontalAlignment: Text.AlignHCenter
            text: "NO NETWORKS FOUND"
            color: body.root.inkDeep
            font.family: body.root.mono
            font.pixelSize: 10
            font.letterSpacing: 2
            opacity: 0.6
        }
    }
}
