#
# Executes commands at login pre-zshrc.
#

#
# Variables
#

# default folders
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_SCREENSHOTS_DIR="$HOME/Pictures/screenshots"

# cleanup HOME directory
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"
export ANSIBLE_HOME="$XDG_DATA_HOME/ansible"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export NIMBLE_DIR="$XDG_DATA_HOME/nimble"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
export W3M_DIR="$XDG_DATA_HOME/w3m"


#export EDITOR=/usr/bin/nano
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

#export GTK_THEME=Arc-Dark
# gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' &>/dev/null & disown

## rofi-emoji stored /usr/share/rofi-emoji/all_emojis.txt
#
export XDG_DATA_DIRS="$HOME/.local/share/data:$XDG_DATA_DIRS"

# tex live config dir
export TEXMFVAR=$HOME/.config/texlive/texmf-var

# Editors --- defined in .aliasrc
#

# if [[ -z "$EDITOR" ]]; then
#   export EDITOR='nano'
# fi
# if [[ -z "$VISUAL" ]]; then
#   export VISUAL='nano'
# fi
# if [[ -z "$PAGER" ]]; then
#   export PAGER='less'
# fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -g cdpath fpath mailpath path
#typeset -gU original

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
### path= (
###   $HOME/{,s}bin(N)
###   /opt/{homebrew,local}/{,s}bin(N)
###   /usr/local/{,s}bin(N)
###   $path
### )

path=(
  $HOME/{bin,sbin}
  /opt/{homebrew,local}/{bin,sbin}
  /usr/local/{bin,sbin}
  $path
)
# add user local bin path 
if [ -d "$HOME/.local/bin" ] && (! echo $PATH | grep -q "$HOME/.local/bin"); then
    export PATH="$HOME/.local/bin:$PATH"
fi
# add cargo bin path
if [ -d "$HOME/.local/share/cargo/bin" ] && (! echo $PATH | grep -q "$HOME/.local/share/carg/bin"); then
    export PATH="$HOME/.local/share/cargo/bin:$PATH"
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
