#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [ -f /etc/bash_completion.d/climate_completion ]; then
	source /etc/bash_completion.d/climate_completion
fi



#-------- External Files {{{
#------------------------------------------------------

# load alias/functions that works with both zsh/bash
if [[ -f ~/.aliasrc ]]; then
    source ~/.aliasrc
fi

# source all files in function directory
if [ -d "$HOME/.config/functions" ]; then
  for f in "$HOME"/.config/functions/*
    do source "$f"
  done
fi

# source command-not-found
if [[ -f "$HOME/.zprezto/modules/command-not-found/init.zsh" ]]; then
  source "$HOME/.zprezto/modules/command-not-found/init.zsh"
fi


#if zplug check zsh-users/zsh-history-substring-search; then
#    bindkey '^[[A' history-substring-search-up
#    bindkey '^[[B' history-substring-search-down
#fi

# zplug load

#bindkey "^[OA" history-substring-search-up
#bindkey "^[OB" history-substring-search-down
eval $(thefuck --alias)


if [[ -f "$HOME/.config/broot/launcher/bash/br" ]]; then
	source "$HOME/.config/broot/launcher/bash/br"
fi


# autocompletion for zsh to get completion of command flags
autoload -U compinit && compinit


# sourcing nvm to install and run different node.js versions
if [[ -f ~/usr/share/nvm/init-nvm.sh ]]; then
	source /usr/share/nvm/init-nvm.sh
fi

# navi command line cheatsheets
source <(echo "$(navi widget zsh)")
