#!/bin/sh

# NSXIV Key Handler Script
#
# Dependencies:
# - xclip (clipboard management)
# - notify-send (notifications)
# - trash-cli (safe file deletion)
# - gimp (image editing)
# - urxvt (terminal emulator)
# - exiv2 (image metadata)
# - jpegtran (JPEG operations)
# - imagemagick (for mogrify command)
# - rawtherapee (RAW image processing)
#
# Available shortcuts:
# C-x: Copy marked filenames to clipboard
# C-c: Copy image to clipboard (as PNG)
# C-i: Copy current image to clipboard
# C-e: View image exif data
# C-g: Open marked images in GIMP
# C-r: Open in RawTherapee
# C-comma: Rotate 270 degrees
# C-period: Rotate 90 degrees
# C-slash: Rotate 180 degrees
# y: Copy current filename to clipboard
# Y: Copy current absolute filename to clipboard
# d: Move file to trash
# G: Open current image in GIMP

process_files() {
    if [ "$NSXIV_USING_NULL" = "1" ]; then
        tr '\0' '\n'
    else
        cat
    fi
}

rotate() {
    degree="$1"
    process_files | while read -r file; do
        case "$(file -b -i "$file")" in
            image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
            *)          mogrify -rotate "$degree" "$file" ;;
        esac
    done
}

process_files | while read -r file; do
    case "$1" in
        "C-x")      echo -n "$file" | tr '\n' ' ' | xclip -selection clipboard ;;
        "C-c")      xclip -selection clipboard -target image/png "$file" ;;
        "C-i")      xclip -selection clipboard -target image/png -i "$file" ;;
        "C-e")      urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & ;;
        "C-g")      gimp "$file" & ;;
        "C-r")      rawtherapee "$file" & ;;
        "C-comma")  rotate 270 ;;
        "C-period") rotate 90 ;;
        "C-slash")  rotate 180 ;;
        "y")        echo -n "$file" | xclip -selection clipboard && 
                    notify-send "$file copied to clipboard" --icon=/home/rx/.local/share/icons/notify/wallpaper.svg & ;;
        "Y")        echo -n "$(readlink -f "$file")" | xclip -selection clipboard && 
                    notify-send "$(readlink -f "$file") copied to clipboard" --icon=/home/rx/.local/share/icons/notify/wallpaper.svg & ;;
        "d")        trash "$file" && 
                    notify-send "$file deleted." --icon=application-exit & ;;
        "G")        gimp "$file" & ;;
    esac
done
