[Scheme]
Name=tokyonight
ColorSelection=#CDD6F4
ColorSelectionUseDefault=FALSE
ColorCursor=#F5E0DC
ColorCursorForeground=#11111B
ColorCursorUseDefault=FALSE
ColorCursor=#a9a9b1b1d6d6
ColorForeground=#a9a9b1b1d6d6
ColorBackground=#1a1a1b1b2626
ColorPalette=#1a1a1b1b2626;#f7f776768e8e;#9e9ecece6a6a;#e0e0afaf6868;#7a7aa2a2f7f7;#9a9a7e7ecccc;#4a4ababaafaf;#acacb0b0d0d0;#4e4e51517373;#f7f776768e8e;#9e9ecece6a6a;#e0e0afaf6868;#7a7aa2a2f7f7;#9a9a7e7ecccc;#4a4ababaafaf;#acacb0b0d0d0


